"""
Phase 2, item 2.2 (IMPROVEMENT_PLAN.md): embedding-space mixup augmentation
for the Stage D classifier, on top of the confirmed-best pipeline so far
(Bangla/DAPT-BanglaBERT text branch -- kept after 2.1 -- + Phase 1's
majority-vote ensembling and ordinal label smoothing).

Same-class mixup only (not cross-class): for each training step, in
addition to the 582 real examples, an equal-sized batch of synthetic
examples is generated by interpolating pairs of same-class aligned
text/image vectors (and raw-text vectors, and confidence vectors) with
lambda ~ Beta(0.4, 0.4). Same-class mixup keeps the label exact (no soft
cross-class label needed on top of the already-soft ordinal-smoothed
target) while effectively doubling the training signal and interpolating
through embedding space between real examples of the same severity level
-- addressing the "582 examples is thin for a 5-way classifier on
~1900-dim features" concern directly, without touching the frozen
encoders or Stage A alignment.

Synthetic pairs are re-sampled every epoch (not fixed once), so the
classifier sees different interpolated points over the course of training
rather than memorizing one fixed augmented set.
"""
import os
import json

import numpy as np
import torch
import torch.nn as nn
from sklearn.metrics import f1_score, classification_report

from train_e6 import (
    E6GatedOrth, load_aligned_data, class_weights_from, NUM_CLASSES, CLASSES, SEEDS,
    MAX_EPOCHS, PATIENCE, LR, DEVICE,
)
from phase1_3_ordinal_smoothing import build_smoothing_matrix, soft_target_loss, TAU

PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
RESULTS_PATH = os.path.join(PROJECT_ROOT, "outputs", "phase2_2_mixup_results.json")

MIXUP_ALPHA = 0.1  # Beta(alpha, alpha) shape parameter -- lower = synthetic points stay closer to one parent (gentler)


def to_tensors(split_data):
    return (
        torch.tensor(split_data["text"], device=DEVICE),
        torch.tensor(split_data["image"], device=DEVICE),
        torch.tensor(split_data["raw_text"], device=DEVICE),
        torch.tensor(split_data["conf"], device=DEVICE),
        torch.tensor(split_data["y"], device=DEVICE),
    )


def make_mixup_batch(X_text, X_img, X_rawtext, X_conf, y, rng):
    """One synthetic example per real example, each formed by interpolating
    it with a randomly chosen OTHER example from the same class."""
    n = X_text.shape[0]
    y_np = y.cpu().numpy()
    partner_idx = np.empty(n, dtype=np.int64)
    for cls in np.unique(y_np):
        cls_idx = np.where(y_np == cls)[0]
        if len(cls_idx) < 2:
            partner_idx[cls_idx] = cls_idx  # only one example of this class -- pairs with itself (no-op)
            continue
        for i in cls_idx:
            choices = cls_idx[cls_idx != i]
            partner_idx[i] = rng.choice(choices)

    partner_idx_t = torch.tensor(partner_idx, device=DEVICE)
    lam = torch.tensor(
        rng.beta(MIXUP_ALPHA, MIXUP_ALPHA, size=n).astype(np.float32), device=DEVICE
    ).unsqueeze(1)

    mix_text = lam * X_text + (1 - lam) * X_text[partner_idx_t]
    mix_img = lam * X_img + (1 - lam) * X_img[partner_idx_t]
    mix_rawtext = lam * X_rawtext + (1 - lam) * X_rawtext[partner_idx_t]
    mix_conf = lam * X_conf + (1 - lam) * X_conf[partner_idx_t]
    # y unchanged -- same-class mixup, label is exact for both parents
    return mix_text, mix_img, mix_rawtext, mix_conf, y


def train_one(seed, data, class_weights, smoothing_matrix):
    torch.manual_seed(seed)
    np.random.seed(seed)
    rng = np.random.default_rng(seed)

    model = E6GatedOrth(NUM_CLASSES).to(DEVICE)
    optimizer = torch.optim.Adam(model.parameters(), lr=LR, weight_decay=1e-4)

    X_text_tr, X_img_tr, X_rawtext_tr, X_conf_tr, y_tr = to_tensors(data["train"])
    X_text_val, X_img_val, X_rawtext_val, X_conf_val, y_val = to_tensors(data["val"])

    best_val_f1 = -1.0
    best_val_probs = None
    epochs_without_improve = 0

    for epoch in range(MAX_EPOCHS):
        model.train()
        optimizer.zero_grad()

        mix_text, mix_img, mix_rawtext, mix_conf, mix_y = make_mixup_batch(
            X_text_tr, X_img_tr, X_rawtext_tr, X_conf_tr, y_tr, rng
        )
        full_text = torch.cat([X_text_tr, mix_text], dim=0)
        full_img = torch.cat([X_img_tr, mix_img], dim=0)
        full_rawtext = torch.cat([X_rawtext_tr, mix_rawtext], dim=0)
        full_conf = torch.cat([X_conf_tr, mix_conf], dim=0)
        full_y = torch.cat([y_tr, mix_y], dim=0)

        out = model(full_text, full_img, full_rawtext, full_conf)
        loss = soft_target_loss(out, full_y, smoothing_matrix, class_weights)
        loss.backward()
        optimizer.step()

        model.eval()
        with torch.no_grad():
            out_val = model(X_text_val, X_img_val, X_rawtext_val, X_conf_val)
            probs_val = torch.softmax(out_val, dim=1)
            pred_val = probs_val.argmax(dim=1)
            val_f1 = f1_score(y_val.cpu().numpy(), pred_val.cpu().numpy(), average="macro", zero_division=0)

        if val_f1 > best_val_f1:
            best_val_f1 = val_f1
            best_val_probs = probs_val.cpu().numpy().copy()
            epochs_without_improve = 0
        else:
            epochs_without_improve += 1
            if epochs_without_improve >= PATIENCE:
                break

    return best_val_f1, best_val_probs, y_val.cpu().numpy()


def main():
    print("Loading aligned embeddings (Bangla pipeline, confirmed best after 2.1)...")
    data = load_aligned_data()
    class_weights = class_weights_from(data["train"]["y"])
    smoothing_matrix = torch.tensor(build_smoothing_matrix(NUM_CLASSES, TAU), device=DEVICE)
    print(f"Mixup alpha={MIXUP_ALPHA}, same-class pairing, resampled every epoch, "
          f"doubling the effective training batch (582 real + 582 synthetic).")

    seed_f1s = []
    seed_probs = []
    y_val = None
    for seed in SEEDS:
        val_f1, probs, y_val = train_one(seed, data, class_weights, smoothing_matrix)
        seed_f1s.append(val_f1)
        seed_probs.append(probs)
        print(f"seed {seed}: val macro-F1 = {val_f1:.4f}")

    seed_preds = np.stack([p.argmax(axis=1) for p in seed_probs])
    majority_pred = np.array([
        np.bincount(seed_preds[:, i], minlength=NUM_CLASSES).argmax()
        for i in range(seed_preds.shape[1])
    ])
    majority_macro_f1 = f1_score(y_val, majority_pred, average="macro", zero_division=0)
    report = classification_report(
        y_val, majority_pred, labels=list(range(NUM_CLASSES)), target_names=CLASSES,
        zero_division=0, output_dict=True,
    )

    print(f"\n=== Mixup augmentation, majority-vote macro-F1: {majority_macro_f1:.4f} ===")
    print(f"Comparison -- Phase 1 best (no augmentation): 0.5330")
    print(f"Delta: {majority_macro_f1 - 0.5330:+.4f}")
    print(f"\nPer-class F1:")
    for c in CLASSES:
        print(f"  {c}: {report[c]['f1-score']:.4f}")

    with open(RESULTS_PATH, "w", encoding="utf-8") as f:
        json.dump({
            "mixup_alpha": MIXUP_ALPHA,
            "seed_f1s": seed_f1s,
            "majority_vote_macro_f1": float(majority_macro_f1),
            "comparison_phase1_best": 0.5330,
            "delta": float(majority_macro_f1 - 0.5330),
            "classification_report": report,
        }, f, indent=2)
    print(f"\nSaved results to {RESULTS_PATH}")


if __name__ == "__main__":
    main()
